Feature/accommodation/entity
WebDevsinGermany/airbnb-backend pull request #4
Opened 2024-01-25 11:59 UTC by casysj

수정사항 커밋해서 올리고보니 기존 pr에 추가 되진 않네요?
그래서 일단 기존 pr 닫고 새로 만들었습니다

2024-01-25 14:25 UTC, indiegolab commented
> 수정사항 커밋해서 올리고보니 기존 pr에 추가 되진 않네요? 그래서 일단 기존 pr 닫고 새로 만들었습니다

회사에서 일 할 때는 수정사항 커밋해서 올렸을 때 기존 PR로 진행했었어요.
세팅 전까지는 일단 진행하죠 ㅋㅋ

2024-01-25 20:16 UTC, kyuhyunhan requested changes

2024-01-25 20:16 UTC, kyuhyunhan commented on .gitignore
> +.prettierrc
gitignore에 eslint랑 prettier는 왜 추가하신건가요??

2024-01-25 20:16 UTC, kyuhyunhan commented on src/accommodation/entity/accommodation.entity.ts
> +  @Column()
오우 이런 툭한 date값들을 위해서 typeorm에 존재하는 데코레이터가 있습니다..!
https://orkhan.gitbook.io/typeorm/docs/decorator-reference#createdatecolumn
요 문서 확인해주세요

2024-01-25 20:37 UTC, casysj commented on .gitignore
> +.prettierrc
eslintrc 같은경우는 제쪽에서 계속 빨간줄 그어지는게 있어서 그거때문에 추가한게 있거든요.
그래서 앞으로는 그런거 건들여도 무시하려고 했는데
정작 추가된 코드는 영향이 없어서 사실 무용지물이긴 하네요

2024-01-25 20:44 UTC, casysj commented on src/accommodation/entity/accommodation.entity.ts
> +  @Column()
적용했습니다

2024-01-26 21:26 UTC, kyuhyunhan commented on src/user/entity/user.entity.ts
> +  profile_picture: Buffer;
Buffer 타입 문제 없이 작동했나요? 제 로컬에서는
```
DataTypeNotSupportedError: Data type "Buffer" in "User.profile_picture" is not supported by "postgres" database.
```
이라고 뜨는데..

2024-01-26 21:26 UTC, kyuhyunhan commented on src/user/entity/user.entity.ts
> +  date_of_birth: Date;
제 로컬에서 작업하다가 든 생각인데, 이 값 그냥 string으로 하는거는 어떤가요? 생년월일만 필요하고 시간이나 timezone정보는 어차피 필요하지 않은데, Date 객체로 둘필요가 있나 싶어졌습니다.

2024-01-26 21:55 UTC, casysj commented on .gitignore
> +.prettierrc
done

2024-01-26 21:55 UTC, merged